(* generated by Ott 0.31, locally-nameless lngen from: ../spec/rules.ott *)
Require Import Metalib.Metatheory.
(** syntax *)
Definition typevar : Set := var.
Definition I : Set := nat.

Inductive l : Set := 
 | lbl_TagIndex (i:I)
 | lbl_TagLeft : l
 | lbl_TagRight : l.

Inductive A : Set :=  (*r value type *)
 | t_tvar_b (_:nat)
 | t_tvar_f (X:typevar)
 | t_rcd (l5:l) (A5:A)
 | t_and (A1:A) (A2:A)
 | t_or (A1:A) (A2:A)
 | t_arrow (A5:A) (B:A)
 | t_forall (B:A)
 | t_top : A
 | t_bot : A.

Inductive Tcov : Set :=  (*r covariant type context *)
 | ty_ctx_covTcovIn (l5:l)
 | ty_ctx_covTcovArr (A5:A)
 | ty_ctx_covTcovAll : Tcov
 | ty_ctx_covTCovInterL (A5:A)
 | ty_ctx_covTCovInterR (A5:A)
 | ty_ctx_covTCovUnionL (A5:A)
 | ty_ctx_covTCovUnionR (A5:A).

(* EXPERIMENTAL *)
(** auxiliary functions on the new list types *)
(** library functions *)
(** subrules *)
(** arities *)
(** opening up abstractions *)
Fixpoint open_A_wrt_A_rec (k:nat) (B5:A) (B_6:A) {struct B_6}: A :=
  match B_6 with
  | (t_tvar_b nat) => 
      match lt_eq_lt_dec nat k with
        | inleft (left _) => t_tvar_b nat
        | inleft (right _) => B5
        | inright _ => t_tvar_b (nat - 1)
      end
  | (t_tvar_f X) => t_tvar_f X
  | (t_rcd l5 A5) => t_rcd l5 (open_A_wrt_A_rec k B5 A5)
  | (t_and A1 A2) => t_and (open_A_wrt_A_rec k B5 A1) (open_A_wrt_A_rec k B5 A2)
  | (t_or A1 A2) => t_or (open_A_wrt_A_rec k B5 A1) (open_A_wrt_A_rec k B5 A2)
  | (t_arrow A5 B) => t_arrow (open_A_wrt_A_rec k B5 A5) (open_A_wrt_A_rec k B5 B)
  | (t_forall B) => t_forall (open_A_wrt_A_rec (S k) B5 B)
  | t_top => t_top 
  | t_bot => t_bot 
end.

Definition open_Tcov_wrt_A_rec (k:nat) (B5:A) (Tcov5:Tcov) : Tcov :=
  match Tcov5 with
  | (ty_ctx_covTcovIn l5) => ty_ctx_covTcovIn l5
  | (ty_ctx_covTcovArr A5) => ty_ctx_covTcovArr (open_A_wrt_A_rec k B5 A5)
  | ty_ctx_covTcovAll => ty_ctx_covTcovAll 
  | (ty_ctx_covTCovInterL A5) => ty_ctx_covTCovInterL (open_A_wrt_A_rec k B5 A5)
  | (ty_ctx_covTCovInterR A5) => ty_ctx_covTCovInterR (open_A_wrt_A_rec k B5 A5)
  | (ty_ctx_covTCovUnionL A5) => ty_ctx_covTCovUnionL (open_A_wrt_A_rec k B5 A5)
  | (ty_ctx_covTCovUnionR A5) => ty_ctx_covTCovUnionR (open_A_wrt_A_rec k B5 A5)
end.

Definition open_Tcov_wrt_A B5 Tcov5 := open_Tcov_wrt_A_rec 0 Tcov5 B5.

Definition open_A_wrt_A B5 B_6 := open_A_wrt_A_rec 0 B_6 B5.

(** terms are locally-closed pre-terms *)
(** definitions *)

(* defns LC_A *)
Inductive lc_A : A -> Prop :=    (* defn lc_A *)
 | lc_t_tvar_f : forall (X:typevar),
     (lc_A (t_tvar_f X))
 | lc_t_rcd : forall (l5:l) (A5:A),
     (lc_A A5) ->
     (lc_A (t_rcd l5 A5))
 | lc_t_and : forall (A1 A2:A),
     (lc_A A1) ->
     (lc_A A2) ->
     (lc_A (t_and A1 A2))
 | lc_t_or : forall (A1 A2:A),
     (lc_A A1) ->
     (lc_A A2) ->
     (lc_A (t_or A1 A2))
 | lc_t_arrow : forall (A5 B:A),
     (lc_A A5) ->
     (lc_A B) ->
     (lc_A (t_arrow A5 B))
 | lc_t_forall : forall (B:A),
      ( forall X , lc_A  ( open_A_wrt_A B (t_tvar_f X) )  )  ->
     (lc_A (t_forall B))
 | lc_t_top : 
     (lc_A t_top)
 | lc_t_bot : 
     (lc_A t_bot).

(* defns LC_Tcov *)
Inductive lc_Tcov : Tcov -> Prop :=    (* defn lc_Tcov *)
 | lc_ty_ctx_covTcovIn : forall (l5:l),
     (lc_Tcov (ty_ctx_covTcovIn l5))
 | lc_ty_ctx_covTcovArr : forall (A5:A),
     (lc_A A5) ->
     (lc_Tcov (ty_ctx_covTcovArr A5))
 | lc_ty_ctx_covTcovAll : 
     (lc_Tcov ty_ctx_covTcovAll)
 | lc_ty_ctx_covTCovInterL : forall (A5:A),
     (lc_A A5) ->
     (lc_Tcov (ty_ctx_covTCovInterL A5))
 | lc_ty_ctx_covTCovInterR : forall (A5:A),
     (lc_A A5) ->
     (lc_Tcov (ty_ctx_covTCovInterR A5))
 | lc_ty_ctx_covTCovUnionL : forall (A5:A),
     (lc_A A5) ->
     (lc_Tcov (ty_ctx_covTCovUnionL A5))
 | lc_ty_ctx_covTCovUnionR : forall (A5:A),
     (lc_A A5) ->
     (lc_Tcov (ty_ctx_covTCovUnionR A5)).
(** free variables *)
(** substitutions *)
(** context application *)
Definition appctx_Tcov (Tcov5:Tcov) (A_6:A) : A :=
  match Tcov5 with
  | (ty_ctx_covTcovIn l5) => (t_rcd l5 A_6)
  | (ty_ctx_covTcovArr A5) => (t_arrow A5 A_6)
  | (ty_ctx_covTcovAll) => (t_forall A_6)
  | (ty_ctx_covTCovInterL A5) => (t_and A_6 A5)
  | (ty_ctx_covTCovInterR A5) => (t_and A5 A_6)
  | (ty_ctx_covTCovUnionL A5) => (t_or A_6 A5)
  | (ty_ctx_covTCovUnionR A5) => (t_or A5 A_6)
end.


(** definitions *)

(* defns DSub *)
Inductive DeclarativeSubtyping : A -> A -> Prop :=    (* defn DeclarativeSubtyping *)
 | DSubRefl : forall (A5:A),
     lc_A A5 ->
     DeclarativeSubtyping A5 A5
 | DSubTrans : forall (A1 A3 A2:A),
     DeclarativeSubtyping A1 A2 ->
     DeclarativeSubtyping A2 A3 ->
     DeclarativeSubtyping A1 A3
 | DSubCov : forall (Tcov5:Tcov) (A5 B:A),
     lc_Tcov Tcov5 ->
     DeclarativeSubtyping A5 B ->
     DeclarativeSubtyping  (appctx_Tcov  Tcov5   A5 )   (appctx_Tcov  Tcov5   B ) 
 | DSubFunCon : forall (A1 B A2:A),
     lc_A B ->
     DeclarativeSubtyping A2 A1 ->
     DeclarativeSubtyping (t_arrow A1 B) (t_arrow A2 B)
 | DSubCovDistI : forall (Tcov5:Tcov) (A5 B:A),
     lc_Tcov Tcov5 ->
     lc_A A5 ->
     lc_A B ->
     DeclarativeSubtyping (t_and  (appctx_Tcov  Tcov5   A5 )   (appctx_Tcov  Tcov5   B ) )  (appctx_Tcov  Tcov5   (t_and A5 B) ) 
 | DSubFunDistU : forall (A1 A2 B1 B2:A),
     lc_A A1 ->
     lc_A B1 ->
     lc_A A2 ->
     lc_A B2 ->
     DeclarativeSubtyping (t_arrow  (t_and A1 A2)   (t_or B1 B2) ) (t_or  (t_arrow A1 B1)   (t_arrow A2 B2) )
 | DSubFunDistI : forall (A1 B A2:A),
     lc_A A1 ->
     lc_A A2 ->
     lc_A B ->
     DeclarativeSubtyping (t_and  (t_arrow A1 B)   (t_arrow A2 B) ) (t_arrow  (t_or A1 A2)  B)
 | DSubEmpty : forall (B:A),
     lc_A B ->
     DeclarativeSubtyping t_bot B
 | DSubTop : forall (A5:A),
     lc_A A5 ->
     DeclarativeSubtyping A5 t_top
 | DSubInterLL : forall (A1 A2 B:A),
     lc_A A2 ->
     DeclarativeSubtyping A1 B ->
     DeclarativeSubtyping (t_and A1 A2) B
 | DSubInterLR : forall (A1 A2 B:A),
     lc_A A1 ->
     DeclarativeSubtyping A2 B ->
     DeclarativeSubtyping (t_and A1 A2) B
 | DSubInterR : forall (A5 B1 B2:A),
     DeclarativeSubtyping A5 B1 ->
     DeclarativeSubtyping A5 B2 ->
     DeclarativeSubtyping A5 (t_and B1 B2)
 | DSubUnionL : forall (A1 A2 B:A),
     DeclarativeSubtyping A1 B ->
     DeclarativeSubtyping A2 B ->
     DeclarativeSubtyping (t_or A1 A2) B
 | DSubUnionRL : forall (A5 B1 B2:A),
     lc_A B2 ->
     DeclarativeSubtyping A5 B1 ->
     DeclarativeSubtyping A5 (t_or B1 B2).

(* defns Ordinary *)
Inductive UnionOrdinary : A -> Prop :=    (* defn UnionOrdinary *)
 | OrdU_top : 
     UnionOrdinary t_top
 | OrdU_bot : 
     UnionOrdinary t_bot
 | OrdU_arrow : forall (A5 B:A),
     lc_A A5 ->
     lc_A B ->
     UnionOrdinary (t_arrow A5 B)
 | OrdU_and : forall (A5 B:A),
     UnionOrdinary A5 ->
     UnionOrdinary B ->
     UnionOrdinary (t_and A5 B)
 | OrdU_rcd : forall (l5:l) (A5:A),
     UnionOrdinary A5 ->
     UnionOrdinary (t_rcd l5 A5)
 | OrdU_forall : forall (L:vars) (A5:A),
      ( forall X , X \notin  L  -> UnionOrdinary  ( open_A_wrt_A A5 (t_tvar_f X) )  )  ->
     UnionOrdinary (t_forall A5)
with IntersectionOrdinary : A -> Prop :=    (* defn IntersectionOrdinary *)
 | OrdI_top : 
     IntersectionOrdinary t_top
 | OrdI_bot : 
     IntersectionOrdinary t_bot
 | OrdI_arrow : forall (A5 B:A),
     UnionOrdinary A5 ->
     IntersectionOrdinary B ->
     IntersectionOrdinary (t_arrow A5 B)
 | OrdI_or : forall (A5 B:A),
     IntersectionOrdinary A5 ->
     IntersectionOrdinary B ->
     IntersectionOrdinary (t_or A5 B)
 | OrdI_rcd : forall (l5:l) (A5:A),
     IntersectionOrdinary A5 ->
     IntersectionOrdinary (t_rcd l5 A5)
 | OrdI_forall : forall (L:vars) (A5:A),
      ( forall X , X \notin  L  -> IntersectionOrdinary  ( open_A_wrt_A A5 (t_tvar_f X) )  )  ->
     IntersectionOrdinary (t_forall A5)
with SplitIntersection : A -> A -> A -> Prop :=    (* defn SplitIntersection *)
 | SpIIntersection : forall (A5 B:A),
     lc_A A5 ->
     lc_A B ->
     SplitIntersection (t_and A5 B) A5 B
 | SpIUnionL : forall (A_5 B A1 A2:A),
     lc_A B ->
     SplitIntersection A_5 A1 A2 ->
     SplitIntersection (t_or A_5 B) (t_or A1 B) (t_or A2 B)
 | SpIUnionR : forall (A5 B B1 B2:A),
     lc_A A5 ->
     SplitIntersection B B1 B2 ->
     SplitIntersection (t_or A5 B) (t_or A5 B1) (t_or A5 B2)
 | SpIFunR : forall (A5 B B1 B2:A),
     lc_A A5 ->
     SplitIntersection B B1 B2 ->
     SplitIntersection (t_arrow A5 B) (t_arrow A5 B1) (t_arrow A5 B2)
 | SpIFunL : forall (A_5 B A1 A2:A),
     lc_A B ->
     SplitUnion A_5 A1 A2 ->
     SplitIntersection (t_arrow A_5 B) (t_arrow A1 B) (t_arrow A2 B)
 | SpIFunTy : forall (L:vars) (A_5 A1 A2:A),
      ( forall X , X \notin  L  -> SplitIntersection  ( open_A_wrt_A A_5 (t_tvar_f X) )   ( open_A_wrt_A A1 (t_tvar_f X) )   ( open_A_wrt_A A2 (t_tvar_f X) )  )  ->
     SplitIntersection (t_forall A_5) (t_forall A1) (t_forall A2)
 | SpIIn : forall (l5:l) (A_5 A1 A2:A),
     SplitIntersection A_5 A1 A2 ->
     SplitIntersection (t_rcd l5 A_5) (t_rcd l5 A1) (t_rcd l5 A2)
with SplitUnion : A -> A -> A -> Prop :=    (* defn SplitUnion *)
 | SpUUnion : forall (A5 B:A),
     lc_A A5 ->
     lc_A B ->
     SplitUnion (t_or A5 B) A5 B
 | SpUIntersectionL : forall (A_5 B A1 A2:A),
     lc_A B ->
     SplitUnion A_5 A1 A2 ->
     SplitUnion (t_and A_5 B) (t_and A1 B) (t_and A2 B)
 | SpUIntersectionR : forall (A5 B B1 B2:A),
     lc_A A5 ->
     SplitUnion B B1 B2 ->
     SplitUnion (t_and A5 B) (t_and A5 B1) (t_and A5 B2)
 | SpUFunR : forall (A5 B B1 B2:A),
     lc_A A5 ->
     SplitUnion B B1 B2 ->
     SplitUnion (t_arrow A5 B) (t_arrow A5 B1) (t_arrow A5 B2)
 | SpUFunL : forall (A_5 B A1 A2:A),
     lc_A B ->
     SplitIntersection A_5 A1 A2 ->
     SplitUnion (t_arrow A_5 B) (t_arrow A1 B) (t_arrow A2 B)
 | SpUFunTy : forall (L:vars) (A_5 A1 A2:A),
      ( forall X , X \notin  L  -> SplitUnion  ( open_A_wrt_A A_5 (t_tvar_f X) )   ( open_A_wrt_A A1 (t_tvar_f X) )   ( open_A_wrt_A A2 (t_tvar_f X) )  )  ->
     SplitUnion (t_forall A_5) (t_forall A1) (t_forall A2)
 | SpUIn : forall (l5:l) (A_5 A1 A2:A),
     SplitUnion A_5 A1 A2 ->
     SplitUnion (t_rcd l5 A_5) (t_rcd l5 A1) (t_rcd l5 A2).


(** infrastructure *)
Hint Constructors DeclarativeSubtyping UnionOrdinary IntersectionOrdinary SplitIntersection SplitUnion lc_A lc_Tcov : core.


